version: "3"
services:
    persistence-bot:
        image: persistencedocker
        build: ./persistencebot/
        ports:
            - 8101:8101

    matrasscrapper:
        image: matrasimage
        build: ./matrasscraper/
        ports:
            - 8102:8102

    googlecrawler:
        image: googleimage
        build: ./googlecrawler/
        ports: 
            - 8105:8105

    gandalfscraper:
        image: gandalfimage
        build: ./gandalfscraper/
        ports:
            - 8106:8106

    czytamplscraper:
        image: czytamplimage
        build: ./czytamplscraper/
        ports: 
            - 8103:8103

    taniaksiazkascraper:
        image: taniaksiazkaimage
        build: ./taniaksiazkascraper
        ports:
            - 8104:8104

    blackbookwebapp:
        image: blackbookwebappimage
        build: ../black-book-webapp/
        ports: 
            - 3000:3000
